name: pr title lint

on:
  pull_request:

jobs:
  pr-title-format:
    name: Lint PR Title
    permissions:
      pull-requests: read
      statuses: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
